spring:
  datasource:
    url: jdbc:h2:mem:data
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    url: jdbc:mysql://localhost:3306/fitness
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: fitness

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: drop-and-create
              create-target: create.sql
              drop-target: create.sql
#
#logging:
#  level:
#    root: debug