server:
  port: 9888

spring:
  datasource:
#    name: fitness
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ceam_sports?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&nullCatalogMeansCurrent=true&allowMultiQueries=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://${MYSQL_HOST:cmysql}:${MYSQL_PORT:3306}/ceam_sports?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&nullCatalogMeansCurrent=true&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: ${MYSQL_ROOT_USERNAME:root}
#    password: ${MYSQL_ROOT_PASSWORD:123456}
    username: root
    password: fitness
    url: jdbc:mysql://localhost:3306/ceam_mall

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      filters: stat
#      maxActive: 20 #最大连接数
#      initialSize: 1 #连接池初始化大小
#      maxWait: 60000
#      minIdle: 1 #最小空闲连接数
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
  redis:
    host: localhost

#jwt
jwt:
  token-header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  secret: k09BQnaF
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认1小时
  validity: 36000000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

# 是否限制单用户登录
single:
  login: false

# 密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAnvwlQrBRPSNNthuG
    zvpR1e4S3saWY0Q28K33wkvyTSITcpRlm0JUwhVgB2tQJB80XfpLFz7jzPnGZQT4
    LeDBiwIDAQABAkBSLxm7zZVRO2yylKwtVmzzX6xViOa4zcxwwh1vTP8mK4ShcTX8
    bPkyHzkby7TJRwWl2qDoWh4ra2t8oHAEmP3RAiEA0ANvMrELeFVwarisp2F5gTHi
    NmCngEy5n0Rw4FCBKQ8CIQDDqUGV5J1/I2sgW2NjGMsJiWZkGD6BPzjkSCj/TFdH
    xQIgHlSh3i5akc1Deww6gJ2B7gisB2nIgritSD/ehZa3fpkCIF/vr67VZ7wdG7vD
    05mVYIiOjFvr30n0O+sCzsdPIUSZAiEAtn5gIvpKIrc/EF6gREczWPTsIgrrl/jo
    JhQECWxlzU0=

file:
  path: D:\bmall\file\
  avatar: D:\bmall\avatar\

#mybatis-plus:
#  mapper-locations: classpath:com/ceam/admin/mapper/*.xml

#mybatis:
#  mapper-locations: classpath:com/ceam/admin/mapper/*.xml

## 开发环境用DEBUG，生产环境是否DEBUG
logging:
  level:
    com.ceam: DEBUG