server:
  port: 9888

spring:
  datasource:
    url: jdbc:h2:mem:data
    driver-class-name: org.h2.Driver
    username: sa
    password:

#    username: root
#    password: fitness
#    url: jdbc:mysql://localhost:3306/ceam_mall
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      filters: stat
#      maxActive: 20 #最大连接数
#      initialSize: 1 #连接池初始化大小
#      maxWait: 60000
#      minIdle: 1 #最小空闲连接数
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
  redis:
    host: localhost

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: drop-and-create
              create-target: create.sql
              drop-target: create.sql


logging:
  level:
    root: debug